stages:
  - linux-build

build-moses-linux:
  image: ubuntu:18.04
  stage: linux-build
  script:
    - apt-get update -y
    - apt-get install -y software-properties-common
    - add-apt-repository -y ppa:deadsnakes/ppa
    - apt-get update -y
    - apt-get install -y python3.8 python3.8-dev python3-pip
    - python3.8 -m pip install pip
    - python3.8 -m pip install virtualenv
    - python3.8 -m virtualenv .pyenv
    - . ./.pyenv/bin/activate
    - python -m pip install -r requirements.txt
    - python -m pip install https://github.com/pyinstaller/pyinstaller/tarball/develop
    - cd clients/python && python3.8 -m setup install && cd -
    - cd moses && export PYTHONOPTIMIZE=1 && pyinstaller -y moses.linux.spec && pyinstaller -y ../cli/tdskt.linux.spec && cp -R dist/tdskt-linux/* dist/moses-linux/
  artifacts:
    paths:
      - moses/dist/moses-linux/

  tags:
    - docker
