title: LA_OPT_NXP_Software_License v5 January 2019
question: To use software provided by NXP on modules based on i.MX8 you have to accept "LA_OPT_NXP_Software_License v5 January 2019". Do you want to accept this license?
filename: nxp-eula.txt
