---
# set to true for platforms that are provided by Toradex
standard: true
# descriptive information
name: python3 arm32v7
version: "1.0"
description: minimal python3 setup on debian
# supported modules (using product id),* means all modules except unsupported ones
supportedmodels: ["*"]
unsupportedmodels: []
# defines base image and dockerfile templates for the containers
baseimage:
  common:
    - torizon/arm32v7-debian-base
    - buster
  debug:
  release:
# names of dockerfile templates
container:
  common:
  debug: debug.dockerfile
  release: release.dockerfile
# defines what languages/runtimes are supported by this platform
runtimes:
  - python3
# information about how containers should run
ports:
  common: { "6502/tcp": null }
  debug: {}
  release: {}
volumes:
  common: {}
  debug: {}
  release: {}
devices:
  common: []
  debug: []
  release: []
privileged: false
extraparms:
  common: {}
  debug: {}
  release: {}
# information about the SDK (if required)
usesdk: false
# set to false to use a container template
# additional platform-specific properties that can be used in projects or plugins
props:
  common: {}
  debug: {}
  release: {}

# additional scripts (docker-compose or shell) that can be used to start/stop
# the container
# If you use dockerfile the container should NOT be started there
dockercomposefile:
  common: null
  debug: null
  release: null
startupscript:
  common: null
  debug: null
  release: null
shutdownscript:
  common: null
  debug: null
  release: null
networks:
  common: []
  debug: []
  release: []
