---
# set to true for platforms that are provided by Toradex
standard: true
# descriptive information
name: TorizonCore Builder Project
version: "1.0"
description: template for TorizonCore Builder project
# supported modules (using product id),* means all modules except unsupported ones
supportedmodels: ["*"]
unsupportedmodels: []
# defines base image and dockerfile templates for the containers
architecture: linux/arm
baseimage:
  common:
    - "torizon/debian"
    - "2-bullseye"
  debug:
  release:
# names of dockerfile templates
container:
  common:
  debug: debug.dockerfile
  release: release.dockerfile
runtimes:
  - tcb
tags:
  - workspace
# information about how containers should run
ports:
  common: {}
  debug: {}
  release: {}
volumes:
  common: {}
  debug: {}
  release: {}
devices:
  common: []
  debug: []
  release: []
privileged: false
extraparms:
  common: {}
  debug: {}
  release: {}
# information about the SDK (if required)
usesdk: false

# additional platform-specific properties that can be used in projects or plugins
props:
  common: {}
  debug: {}
  release: {}

# additional scripts (docker-compose or shell) that can be used to start/stop
# the container
# If you use docker-compose file the application container should NOT be listed in the services, since it will be started by the debugger
dockercomposefile:
  common: null
  debug: null
  release: null
startupscript:
  common: null
  debug: null
  release: null
shutdownscript:
  common: null
  debug: null
  release: null
networks:
  common: []
  debug: []
  release: []
